
# tools 
# path to oarfish (>= 0.4)
oarfish_prev: "/mnt/scratch1/lr_quant_benchmarks/software/oarfish_0.4/target/release/oarfish"
# path to oarfish (>= v0.5)
oarfish: "/mnt/scratch1/lr_quant_benchmarks/software/oarfish_0.5/target/release/oarfish"
# path to kallisto (>= v0.51.0)
kallisto: "/mnt/scratch1/lr_quant_benchmarks/software/kallisto-0.51.0/build/src/kallisto"
# path to kallisto (>= v0.43.2)
bustools: "/mnt/scratch1/lr_quant_benchmarks/software/bustools/build/src/bustools"
# path to NanoCount (>= v1.1.0)
nanocount: "NanoCount"
# path to minimap2 (>= 2.28-r1209)
minimap2: "minimap2"
# path to samtools (>= v1.10)
samtools: "samtools"

# where scripts live
script_dir: "/mnt/scratch1/lr_quant_benchmarks/scripts/"

# top level for input files
path_dir: "/mnt/scratch1/lr_quant_benchmarks/input/transigner/"
# where reads live
data_dir: "/mnt/scratch1/lr_quant_benchmarks/input/transigner/dataset/"
# where references live
ref_dir: "/mnt/scratch1/lr_quant_benchmarks/input/transigner/reference/"

# top-level results dir
result_dir: "/mnt/scratch1/lr_quant_benchmarks/results/transigner/"
# where alignments go
alignment_dir: "/mnt/scratch1/lr_quant_benchmarks/results/transigner/alignment/"
# where indices will be written
index_dir: "/mnt/scratch1/lr_quant_benchmarks/input/transigner/indexes/"

# names for specific data files
transcriptome: "GCF_000001405.40_GRCh38.p14_rna.fna"
gtf_file: "GCF_000001405.40_GRCh38.p14_genomic.gtf"
junc_bed: "GCF_000001405.40_GRCh38.p14_junc.bed"
genome_file: "GCF_000001405.40_GRCh38.p14_genomic.fna"
t2g: "GCF_000001405.40_GRCh38.p14.t2g"

data:
    cdna: "1DcDNA/cdna_s1_reads_shuffled.fastq.gz"
    drna: "directRNA/drna_s1_reads_shuffled.fastq.gz"
