# tools 
# path to oarfish (>= 0.4)
oarfish_prev: "/mnt/scratch1/lr_quant_benchmarks/software/oarfish_0.4/target/release/oarfish"
# path to oarfish (>= v0.5)
oarfish: "/mnt/scratch1/lr_quant_benchmarks/software/oarfish_0.5/target/release/oarfish"
# path to kallisto (>= v0.51.0)
kallisto: "/mnt/scratch1/lr_quant_benchmarks/software/kallisto-0.51.0/build/src/kallisto"
# path to kallisto (>= v0.43.2)
bustools: "/mnt/scratch1/lr_quant_benchmarks/software/bustools/build/src/bustools"
# path to NanoCount (>= v1.1.0)
nanocount: "NanoCount"
# path to minimap2 (>= 2.28-r1209)
minimap2: "minimap2"
# path to samtools (>= v1.10)
samtools: "samtools"

# where scripts live
script_dir: "/mnt/scratch1/lr_quant_benchmarks/scripts/"

# top level to input
path_dir: "/mnt/scratch1/lr_quant_benchmarks/input/isoquant/"
# where read sets ilve
data_dir: "/mnt/scratch1/lr_quant_benchmarks/input/isoquant/datatset/"
# where references live
ref_dir: "/mnt/scratch1/lr_quant_benchmarks/input/isoquant/reference/"

# top level to results
result_dir: "/mnt/scratch1/lr_quant_benchmarks/results/isoquant/"
# where alignments go
alignment_dir: "/mnt/scratch1/lr_quant_benchmarks/results/isoquant/alignment/"
# where indices will be written
index_dir: "/mnt/scratch1/lr_quant_benchmarks/results/isoquant/indexes/"

transcriptome: "txps_assembled.fa"
gtf_file: "lrgasp_gencode_vM27_sirvs.gtf"
junc_bed: "lrgasp_gencode_vM27_sirvs_junc.bed"
genome_file: "lrgasp_grcm39_sirvs.fasta"

data:
    ONT: "Mouse.ONT.R10.4.simulated.shuffled.fastq.gz"
    PacBio: "Mouse.PB.simulated.shuffled.fastq.gz"
