# tools 
# path to oarfish (>= v0.9.0)
oarfish: "../../software/oarfish/target/release/oarfish"
# path to kallisto (>= v0.51.1)
kallisto: "../../software/kallisto/kallisto"
# path to bustools (>= v0.44.1)
bustools: "../../software/bustools/bustools"
# path to NanoCount (>= v1.1.0.post2)
nanocount: "NanoCount"
# path to minimap2 (>= 2.28-r1209)
minimap2: "minimap2"
# path to samtools (>= v1.21)
samtools: "samtools"

#number of threads 
threads: 32

# where scripts live
script_dir: "../../scripts/"

# top level to input
path_dir: "../../input/DRSim/"
# where read sets ilve
data_dir: "../../input/DRSim/datatset/"
# where references live
ref_dir: "../../input/DRSim/reference/"

# top level to results
result_dir: "../../results/DRSim/"
# where alignments go
alignment_dir: "../../results/DRSim/alignment/"
# where indices will be written
index_dir: "../../results/DRSim/indexes/"

# names for specific data files
transcriptome: "GCF_000001405.40_GRCh38.p14_rna.fna"
gtf_file: "GCF_000001405.40_GRCh38.p14_genomic.gtf"
junc_bed: "GCF_000001405.40_GRCh38.p14_junc.bed"
genome_file: "GCF_000001405.40_GRCh38.p14_genomic.fna"
t2g: "GCF_000001405.40_GRCh38.p14.t2g"

data:
    drna: "directRNA/truncated_w_errors_reads_14M_shuffled_rev_comp.fastq.gz"
